# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20170720_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 4, 50, 14, 169778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 4, 50, 14, 169778, tzinfo=utc)),
        ),
    ]
